title: Project

pages: true
  template: project

columns:
  - width: 2/3
    fields:
      title:
        label: Title
        type:  text

      created:
        label: Datum
        type:  date
        default: today
        width: 1/2

      showslider:
        label: Homepage
        type: toggle
        text: show project on homepage
        width: 1/2

      intro:
        label: Intro
        type:  textarea  
      
      videolink:
        label: Video
        type:  text

      text:
        label: Text
        type:  textarea

  - width: 1/3
    sections:      
      pages:
        type: pages
        create: default
      files:
        sortable: true